id: PE0745FD7
initial_creation_type: input
source_metadata:
  title: Trulshik Rinpoche Series
  language: es
  description: Texts by and about Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö ('khrul
    zhig ngag dbang chos kyi blo gros, 1924–2011), one of the teachers of His Holiness
    the Fourteenth Dalai Lama.
  volume:
    e6a2e59399434d36bea5f0d78dd665b3:
      title: Advice for Retreat
      parent: Advice
    ab9640bdbb954be6b67a8173ef66ac5b:
      title: Advice for Tenzin Jamchen
      parent: Advice
    a52866adc193452d8e6ca204511263cf:
      title: Advice in Four Lines
      parent: Advice
    d711ac293725406d8bd53eeea5deef2c:
      title: A Prayer for Translators
      parent: Aspiration Prayers
    419d2bf4d3ed4f3e89fc6ff2ad9349c4:
      title: A Prayer for the Spread of Kyabje Dilgo Khyentse Rinpoche’s Termas
      parent: Aspiration Prayers
    fe77210b9bda4f76b0e9e01b62efa655:
      title: Prayer of the View, Meditation and Conduct
      parent: Aspiration Prayers
    f0749d6a177945458875cdc8417a78a7:
      title: Profound Prayer of Aspiration
      parent: Aspiration Prayers
    f436bf053255490ba56dfea2ae141eee:
      title: 'The Quintessential Blessing: A Guru Yoga'
      parent: Guru Yoga
    41cf69cf1d9c4eb08a79c4f6630f35a9:
      title: 'Granting the Wish for Immortality: A Prayer for the Long Life of Dzarong
        Trulshik Rinpoche, the Representative of Guru Rinpoche'
      parent: Long Life Prayers
    19e0df4b30ca442fb88ffdc2c187fb5b:
      title: Long Life Prayer for Alak Zenkar Rinpoche
      parent: Long Life Prayers
    30939bd958f94f079227be86c4070623:
      title: Long Life Prayer for Kyabje Dzarong Trulshik Rinpoche
      parent: Long Life Prayers
    30141ee30a0c46ac976ba21f4d65ec6a:
      title: Long Life Prayer for Lodi Gyari Rinpoche
      parent: Long Life Prayers
    3111f6e7faa8444aab420f07f368872d:
      title: Long Life Prayer for Mayum Tsering Wangmo
      parent: Long Life Prayers
    cee5aeeb88cc4226a83bee11249b5ba4:
      title: Prayer for the Long Life of Chökyi Nyima Rinpoche
      parent: Long Life Prayers
    bb009998a9f64c89bf15cb36cfbc9569:
      title: Prayer for the Long Life of Dilgo Khyentsé II of Shechen, Urgyen Tenzin
        Jigme Lhundrup
      parent: Long Life Prayers
    ff212d8c3b8d4321816fe843ae6094b1:
      title: Prayer for the Long Life of His Holiness the Fourteenth Dalai Lama
      parent: Long Life Prayers
    13c37290b21d4b65b695636fa67205ae:
      title: Prayer for the Long Life of Sogyal Rinpoche—chimé kunnyé
      parent: Long Life Prayers
    f8de78bdc19442838400c2a3ff4a387d:
      title: Prayer for the Long Life of Sogyal Rinpoche—sönam jewé
      parent: Long Life Prayers
    75a03b9487564c6090ace35157acdcfa:
      title: Prayer for the Long Life of Taklung Tsetrul Rinpoche
      parent: Long Life Prayers
    4ed703d9a6b842338d3f844d6a483d4a:
      title: The Attainment of Immortality
      parent: Long Life Prayers
    2cfb302844184936af63917efe92d87c:
      title: A Homage to His Holiness the Dalai Lama
      parent: Praise
    09028222f87445d7a1229b33d23799f5:
      title: Verses of Homage
      parent: Praise
    fde225172b924790a1bf9b87f6855fdd:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: Praise
    4a959946aeab49e1a71d5c400b06d810:
      title: A Record of the Successive Incarnations
      parent: Prayers
    e077c0f198534d219916817022a06278:
      title: 'Gateway for the Faithful: A Supplication Recalling the Lives and Liberation
        of Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö'
      parent: Prayers
    ad892ed806ab4b159dc189aee51ac52d:
      title: A Brief Daily Practice of Damdrip Nyepa Kunsel
      parent: Sādhanas
    5c6d3f4b84e54b34a5c4503c3f136147:
      title: Prayer for the Swift Rebirth of Kyabjé Trulshik Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T01:52:59.290283'
last_modified_at: '2022-03-01T01:52:59.290287'
